### ISSUE TITLE
Issues with responsive scaling

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#140]
*Issue migrated from trac ticket # 140*

**component:** unknown | **priority:** major

#### 2017-04-16 15:30:52: derpeter created the issue

___
There are some intermediate states with errant behaviour. See attached screenshots.

**Comment by jjeising** [comment]
@a-tze Is this still reproducible?

**Comment by a-tze** [comment]
![screenshot-23](https://user-images.githubusercontent.com/8227685/32698265-c26cc058-c7a2-11e7-8409-7110ff41f774.png)

This is a minor glitch I could find, the original behaviour seems to be corrected

**Comment by saerdnaer** [comment]
Looks like this issue was resolved:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/40266/54498351-93cfa080-4906-11e9-8a40-e82c6213aa4d.png">

**Comment by jjeising** [comment]
> Looks like this issue was resolved:

Nope, you've just used wider preview. This is not resolved and will probably stay open until a complete rework of the CSS.
